apiVersion: apps/v1
kind: Deployment
metadata:
  name: exchange
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exchange
  template:
    metadata:
      labels:
        app: exchange
    spec:
      containers:
        - name: exchange
          image: ghcr.io/njwgroeneveld/kubernetes/exchange:latest
          imagePullPolicy: Always
