apiVersion: apps/v1
kind: Deployment
metadata:
  name: exchange
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exchange
  template:
    metadata:
      labels:
        app: exchange
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8001"
    spec:
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: exchange
        image: ghcr.io/njwgroeneveld/kubernetes/exchange:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8001 # Metrics
        - containerPort: 8080 # TCP Orders
        - containerPort: 9999 # UDP Market Data (niet strikt nodig hier, maar netjes)
          protocol: UDP
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "200m" # Iets verhoogd voor als je CPU-stress op de Exchange test
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: exchange-service # Naam ingekort voor makkelijker gebruik in de Trader
  labels:
    app: exchange
    release: prometheus
spec:
  ports:
    - name: metrics
      port: 8001
      targetPort: 8001
    - name: orders
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: exchange
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: exchange-monitor
  namespace: monitoring # Zorg dat deze in dezelfde namespace staat als je trader-monitor
  labels:
    release: monitoring # DIT LABEL IS CRUCIAAL. Check even met 'k get prometheus -n monitoring -o yaml | grep serviceMonitorSelector' of dit klopt
spec:
  selector:
    matchLabels:
      app: exchange # Dit moet matchen met het label in je exchange-service
  namespaceSelector:
    any: true
  endpoints:
  - port: metrics # Dit verwijst naar de naam 'metrics' (poort 8001) in je exchange-service
    interval: 15s
