{
 "title": "Pi5 Cluster: Master Dashboard (with Chaos)",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(node_netstat_Tcp_RetransSegs, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "market data stale",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "trader_market_data_stale", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "System Success Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (\r\n  sum(rate(trader_tcp_order_failures_total[1m])) \r\n  / sum(rate(trader_tcp_orders_total[1m]))\r\n)) * 100\r\nor vector(100)"
    }
   ]
  },
  {
   "title": "Simulated Errors / Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum by (trader_id) (rate(trader_tcp_order_failures_total[1m]))\r\nor\r\nsum by (trader_id) (rate(trader_tcp_orders_total[1m]) * 0)",
     "legendFormat": "{{error_code}} ({{trader_id}})"
    }
   ]
  },
  {
   "title": "UDP Network Flow: Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(exchange_udp_packets_sent_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UDP Network Flow: Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 8 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(trader_udp_prices_total[1m]))",
     "legendFormat": "{{pod}} (Received)"
    }
   ]
  },
  { "title": "🚀 Trading Pipeline Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Order Velocity per Trader",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(exchange_orders_received_total[1m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "📈 Latency & Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Trading Latency Distribution (Heatmap)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(trader_receive_latency_seconds_bucket[5m])) by (le)"
    }
   ]
  },
  {
   "title": "p99 vs Average Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(trader_receive_latency_seconds_bucket[1m])))",
     "legendFormat": "p99 Tail Latency"
    },
    {
     "expr": "rate(trader_receive_latency_seconds_sum[1m]) / rate(trader_receive_latency_seconds_count[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "🖥️ Infrastructure (Nodes & Pods)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true
  },
  {
   "title": "CPU Usage per Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"trader.*|exchange.*\", container!=\"\"}[5m])) by (pod, instance)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{pod=~\"trader.*|exchange.*\", container!=\"\"}) by (pod, instance)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "TCP Retransmits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
   "targets": [
    {
     "expr": "sum(rate(node_netstat_Tcp_RetransSegs{instance=~\"$node.*\"}[1m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU throtteled",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_periods_total{namespace=\"default\", container!=\"\"}[5m])) by (pod)\r\n/\r\nsum(rate(container_cpu_cfs_periods_total{namespace=\"default\", container!=\"\"}[5m])) by (pod)\r\n* 100",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}