apiVersion: apps/v1
kind: Deployment
metadata:
  name: trader
spec:
  replicas: 3 # Nu krijg je 3 verschillende traders in je dashboard
  selector:
    matchLabels:
      app: trader
  template:
    metadata:
      labels:
        app: trader
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: trader
          image: ghcr.io/njwgroeneveld/kubernetes/trader:latest # Check of dit je nieuwe image naam is!
          imagePullPolicy: Always
          env:
            - name: EXCHANGE_URL
              value: "http://exchange-service:8080/order"
            - name: UDP_PORT
              value: "9999"
          ports:
            - containerPort: 8080
              name: chaos-api
            - containerPort: 9090
              name: prom-metrics
            - containerPort: 9999
              name: udp-input
              protocol: UDP
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"  # Ruimer voor de CPU stress-test
              memory: "300Mi" # Ruimer voor de Memory stress-test (OOMKill simulatie)
