apiVersion: v1
kind: Service
metadata:
  name: trader-service # Gebruik deze naam in je Exchange code/env
  labels:
    app: trader
    release: prometheus
spec:
  clusterIP: None # Maakt het 'Headless' voor UDP discovery
  selector:
    app: trader
  ports:
    - name: chaos-api
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: prom-metrics
      port: 9090
      targetPort: 9090
      protocol: TCP
    - name: udp-market-data
      port: 9999
      targetPort: 9999
      protocol: UDP
