apiVersion: v1
kind: Pod
metadata:
  name: cpu-stress
  namespace: default
spec:
  containers:
  - name: cpu-stress
    image: alexeiled/stress-ng
    args: ["--cpu", "1", "--timeout", "300"]
    resources:
      limits:
        cpu: "10m"
